backend:
  name: github
  repo: ZachJHall/Rescue-Midwest
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'


media_folder: static/img
public_folder: /img

collections:
  - name: dogs
    identifier_field: name
    label: Dogs
    folder: dogs
    create: true
    fields:
      - { name: name, label: Name }
      - { name: age, label: Age, widget: number }
      - { name: weight, label: Weight, widget: number }
      - { name: gender, label: Gender(Blue if the dog is male), widget: boolean, default: true }
      - { name: description, label: Description, widget: markdown }
      - { name: thumbnail, label: Image, widget: image, default: static/img/sun-mountains-gradient-colorful-art.jpg}
